sensor:
  vertical: [0.0, -1.0, 0.0]

stairs:
  # base of stairs was [0.0, 1.0, 0.762], but misses first stair
  - origin: [-0.05, 0.62, 1.035]
    direction: [0.04, -0.06, 0.993]
    rise: 0.184
    run: 0.273
    width: 1.1684
