sensor:
  vertical: [0.0, -1.0, 0.0]

stairs:
  - origin: [-0.12, 0.62, 1.035]
    direction: [0.046, -0.064, 0.996]
    rise: 0.173
    run: 0.277
    width: 1.1684
    num_stairs: [9, 10]
    can_miss_first_stair: true
